import Matter from "https://cdn.jsdelivr.net/npm/matter-js@0.20.0/+esm";
const {Engine,Render,Runner,Bodies,Body,Composite,Events}=Matter;
const W=900,H=1600,FINISH_Y=1515,MAX=80;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const el={canvas:$("#arenaCanvas"),stage:$("#arenaStage"),numberTab:$("#numberModeTab"),customTab:$("#customModeTab"),numberPanel:$("#numberModePanel"),customPanel:$("#customModePanel"),start:$("#rangeStart"),end:$("#rangeEnd"),apply:$("#applyRange"),input:$("#participantInput"),count:$("#participantCount"),shuffle:$("#shuffleButton"),mapGrid:$("#mapGrid"),mapCount:$("#mapCount"),mapName:$("#activeMapName"),randomMap:$("#randomizeMap"),winnerMode:$("#winnerMode"),rankField:$("#rankField"),rank:$("#winnerRank"),chaos:$("#chaosToggle"),startRace:$("#startButton"),validation:$("#validationMessage"),speed:$$('[data-speed]'),shake:$("#shakeButton"),reset:$("#resetButton"),ranking:$("#rankingList"),finishCount:$("#finishCount"),status:$("#raceStatus"),countdown:$("#countdown"),winner:$("#winnerOverlay"),winnerLabel:$("#winnerModeLabel"),winnerName:$("#winnerName"),winnerSub:$("#winnerSubtext"),again:$("#raceAgainButton"),confetti:$("#confettiLayer"),rankingPanel:$(".ranking-panel")};
const maps=[{id:"neon-grid",name:"NEON GRID"},{id:"switchback",name:"SWITCHBACK"},{id:"vortex",name:"VORTEX"},{id:"dropzone",name:"DROPZONE"}];
const s={mode:"number",labels:[],map:"neon-grid",winner:"first",speed:1,engine:null,render:null,runner:null,balls:[],rotors:[],rankings:[],running:false,started:0,lastChaos:0,winnerShown:false};
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function msg(v=""){el.validation.textContent=v}
function parse(raw){const out=[];for(const c of String(raw).split(/[\n,]/).map(v=>v.trim()).filter(Boolean)){const m=c.match(/^(.*?)(?:\*(\d+))?$/),label=(m?.[1]||"").trim(),n=Math.min(20,Math.max(1,Number(m?.[2]||1)));if(!label)continue;for(let i=0;i<n&&out.length<MAX;i++)out.push(label);if(out.length>=MAX)break}return out}
function sync(){el.count.textContent=s.labels.length;el.finishCount.textContent=`${s.rankings.length} / ${s.labels.length}`;el.rank.max=Math.max(1,s.labels.length)}
function range(){const a=Math.trunc(Number(el.start.value)),b=Math.trunc(Number(el.end.value));if(!Number.isFinite(a)||!Number.isFinite(b))return msg("숫자 범위를 확인해 주세요.");const n=Math.abs(b-a)+1;if(n>MAX)return msg(`구슬은 최대 ${MAX}개까지 가능합니다.`);const step=a<=b?1:-1;s.labels=Array.from({length:n},(_,i)=>String(a+i*step));el.input.value=s.labels.join(", ");s.rankings=[];sync();msg();preview()}
function setMode(mode){s.mode=mode;const number=mode==="number";el.numberTab.classList.toggle("active",number);el.customTab.classList.toggle("active",!number);el.numberPanel.classList.toggle("hidden",!number);el.customPanel.classList.toggle("hidden",number);el.numberTab.setAttribute("aria-selected",number);el.customTab.setAttribute("aria-selected",!number)}
function custom(){s.labels=parse(el.input.value);sync()}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setMap(id){if(s.running)return;s.map=id;const i=maps.findIndex(m=>m.id===id);el.mapName.textContent=maps[i].name;el.mapCount.textContent=`${String(i+1).padStart(2,"0")} / 04`;$$('.map-card').forEach(c=>c.classList.toggle("active",c.dataset.map===id));preview()}
function setWinner(v){s.winner=v;el.winnerMode.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.winner===v));el.rankField.classList.toggle("hidden",v!=="rank")}
function rect(x,y,w,h,a=0,c="#263257"){return Bodies.rectangle(x,y,w,h,{isStatic:true,angle:a,restitution:.82,friction:.02,render:{fillStyle:c,strokeStyle:c,lineWidth:1}})}
function peg(x,y,r=9,c="#55e7ff"){return Bodies.circle(x,y,r,{isStatic:true,restitution:1.08,friction:0,render:{fillStyle:c,strokeStyle:"#ffffff55",lineWidth:1}})}
function add(b){Composite.add(s.engine.world,b);return b} function many(b){Composite.add(s.engine.world,b)}
function bounds(){many([rect(-14,H/2,36,H,0,"#1b2440"),rect(W+14,H/2,36,H,0,"#1b2440"),rect(W/2,-18,W,40,0,"#1b2440"),rect(95,1490,250,18,-.14,"#2c385f"),rect(W-95,1490,250,18,.14,"#2c385f")])}
function rotor(x,y,w,speed,color){const b=add(rect(x,y,w,12,0,color));s.rotors.push({body:b,speed})}
function neon(){const b=[];for(let row=0;row<12;row++){const y=250+row*92,off=row%2?82:38;for(let x=off;x<W-30;x+=105)b.push(peg(x,y,row%3===0?11:8,row%2?"#55e7ff":"#6f7cff"))}many(b);rotor(450,735,185,.025,"#ff63c3");rotor(450,1100,220,-.018,"#b7ff5a")}
function switchback(){const b=[];[[300,310,520,18,.12],[610,500,500,18,-.13],[285,690,470,18,.14],[610,875,500,18,-.14],[290,1060,470,18,.13],[600,1240,480,18,-.13]].forEach((r,i)=>b.push(rect(...r,i%2?"#b7ff5a":"#55e7ff")));[390,575,760,945,1130,1315].forEach((y,i)=>b.push(peg(i%2?790:110,y,20,"#ff63c3")));many(b);rotor(120,615,130,.035,"#ffc857");rotor(780,970,130,-.032,"#ffc857")}
function vortex(){const b=[],cx=450,cy=820;[330,250,170].forEach((r,ring)=>{const gap=3+ring*4;for(let i=0;i<14;i++){if(i===gap||i===(gap+1)%14)continue;const a=Math.PI*2*i/14+ring*.22;b.push(rect(cx+Math.cos(a)*r,cy+Math.sin(a)*r,110,13,a+Math.PI/2,ring===1?"#ff63c3":"#55e7ff"))}});for(let i=0;i<14;i++){const a=i/14*Math.PI*2;b.push(peg(cx+Math.cos(a)*95,cy+Math.sin(a)*95,9,"#ffc857"))}many(b);rotor(cx,cy,240,.028,"#b7ff5a")}
function dropzone(){const b=[];[[180,340,32],[450,300,28],[720,350,32],[310,520,38],[590,540,38],[150,720,30],[450,700,46],[750,735,30],[280,910,34],[620,930,34],[120,1110,26],[360,1080,40],[560,1110,40],[790,1085,26],[450,1290,45]].forEach((p,i)=>b.push(peg(...p,i%3===0?"#ffc857":i%3===1?"#55e7ff":"#ff63c3")));b.push(rect(230,1350,360,16,.2,"#6f7cff"),rect(670,1350,360,16,-.2,"#6f7cff"),rect(235,610,260,14,-.18,"#b7ff5a"),rect(665,610,260,14,.18,"#b7ff5a"));many(b);rotor(450,1000,240,-.036,"#ff63c3")}
function destroy(){if(s.runner)Runner.stop(s.runner);if(s.render){Render.stop(s.render);s.render.textures={}}if(s.engine)Composite.clear(s.engine.world,false,true);s.engine=s.render=s.runner=null;s.balls=[]}
function init(){destroy();s.engine=Engine.create();s.engine.gravity.x=0;s.engine.gravity.y=1.05;s.engine.gravity.scale=.001;s.engine.timing.timeScale=s.speed;s.render=Render.create({canvas:el.canvas,engine:s.engine,options:{width:W,height:H,wireframes:false,background:"transparent",pixelRatio:Math.min(devicePixelRatio||1,2)}});s.runner=Runner.create();s.rotors=[];bounds();({"neon-grid":neon,switchback,vortex,dropzone}[s.map])();Events.on(s.engine,"afterUpdate",tick);Events.on(s.render,"afterRender",draw);Render.run(s.render);Runner.run(s.runner,s.engine)}
function hue(t,i){let h=0;for(const c of String(t))h=(h*31+c.charCodeAt(0))|0;return `hsl(${Math.abs(h+i*47)%360} 86% 62%)`}
function spawn(){s.balls=s.labels.map((label,i)=>{const col=i%12,row=Math.floor(i/12),r=s.labels.length>55?14:s.labels.length>35?16:18,b=Bodies.circle(Math.max(45,Math.min(W-45,66+col*70+(row%2?22:0)+(Math.random()-.5)*10)),48+row*27+Math.random()*8,r,{restitution:.66,friction:.005,frictionAir:.002,density:.0022,render:{fillStyle:hue(label,i),strokeStyle:"#ffffffaa",lineWidth:2}});b.plugin={marble:true,name:label,finished:false,index:i};Body.setVelocity(b,{x:(Math.random()-.5)*1.5,y:0});return b});many(s.balls)}
function draw(){if(!s.render)return;const c=s.render.context;c.save();c.strokeStyle="#55e7ff88";c.setLineDash([12,11]);c.lineWidth=2;c.beginPath();c.moveTo(120,FINISH_Y);c.lineTo(W-120,FINISH_Y);c.stroke();c.setLineDash([]);c.font="900 12px monospace";c.fillStyle="#55e7ff";c.textAlign="center";c.fillText("FINISH",W/2,FINISH_Y-11);for(const b of s.balls){if(b.plugin.finished)continue;const r=b.circleRadius||18,n=String(b.plugin.name),shown=n.length>(r<=14?3:5)?n.slice(0,r<=14?2:4)+"…":n;c.font=`900 ${r<=14?10:12}px system-ui`;c.fillStyle="#050713";c.textBaseline="middle";c.fillText(shown,b.position.x,b.position.y)}c.restore()}
function tick(){if(!s.engine)return;for(const r of s.rotors)Body.rotate(r.body,r.speed*s.speed);if(!s.running)return;const now=performance.now();if(el.chaos.checked&&now-s.lastChaos>1800/s.speed){s.lastChaos=now;const d=Math.random()>.5?1:-1;for(const b of s.balls)if(!b.plugin.finished&&Math.random()<.55)Body.applyForce(b,b.position,{x:d*(.000035+Math.random()*.000045),y:-Math.random()*.000018});el.stage.animate([{filter:"brightness(1)"},{filter:"brightness(1.12)"},{filter:"brightness(1)"}],{duration:240})}for(const b of s.balls)if(!b.plugin.finished&&b.position.y>=FINISH_Y)finish(b)}
function finish(b){if(b.plugin.finished)return;b.plugin.finished=true;s.rankings.push({label:b.plugin.name,time:(performance.now()-s.started)/1000});Composite.remove(s.engine.world,b);renderRanks();declare()}
function target(){return s.winner==="first"?1:s.winner==="last"?s.labels.length:Math.max(1,Math.min(s.labels.length,Math.trunc(Number(el.rank.value)||1)))}
function renderRanks(){sync();if(!s.rankings.length){el.ranking.innerHTML='<li class="ranking-empty">경기를 시작하면<br />여기에 순위가 쌓입니다.</li>';return}const w=target()-1;el.ranking.innerHTML=s.rankings.slice(0,22).map((r,i)=>`<li class="rank-item ${i===w?"winner":""}"><span class="rank-num">${String(i+1).padStart(2,"0")}</span><span class="rank-name">${esc(r.label)}</span><span class="rank-time">${r.time.toFixed(2)}s</span></li>`).join("")}
function declare(){const t=target();if(s.winnerShown||s.rankings.length<t)return;const r=s.rankings[t-1];s.winnerShown=true;s.running=false;s.engine.timing.timeScale=0;el.startRace.disabled=false;el.startRace.querySelector("span").textContent="START RACE";el.rankingPanel.classList.remove("race-running");el.status.textContent="RACE COMPLETE";el.winnerLabel.textContent=s.winner==="last"?"LAST MARBLE":s.winner==="rank"?`${t}TH PICK`:"WINNER";el.winnerName.textContent=r.label;el.winnerSub.textContent=s.winner==="last"?"마지막으로 도착":`${t}번째로 도착`;el.winner.classList.remove("hidden");confetti()}
function countdown(){return new Promise(resolve=>{const a=["3","2","1","GO!"],go=i=>{el.countdown.textContent=a[i];el.countdown.animate([{transform:"scale(.72)",opacity:0},{transform:"scale(1)",opacity:1},{transform:"scale(1.08)",opacity:0}],{duration:650});if(i<a.length-1)setTimeout(()=>go(i+1),700);else setTimeout(()=>{el.countdown.textContent="";resolve()},610)};go(0)})}
async function race(){if(s.running)return;if(s.mode==="custom")custom();if(s.labels.length<2)return msg("참가자를 2개 이상 넣어 주세요.");msg();s.rankings=[];s.winnerShown=false;el.winner.classList.add("hidden");el.ranking.innerHTML='<li class="ranking-empty">곧 출발합니다…</li>';sync();el.startRace.disabled=true;el.startRace.querySelector("span").textContent="RACING";el.status.textContent="COUNTDOWN";el.rankingPanel.classList.add("race-running");init();s.engine.timing.timeScale=0;spawn();await countdown();s.started=performance.now();s.lastChaos=s.started;s.running=true;s.engine.timing.timeScale=s.speed;el.status.textContent="LIVE RACE"}
function setSpeed(v){s.speed=v;el.speed.forEach(b=>b.classList.toggle("active",Number(b.dataset.speed)===v));if(s.engine&&s.running)s.engine.timing.timeScale=v}
function shakeRace(){if(!s.engine||!s.running)return;for(const b of s.balls)if(!b.plugin.finished)Body.applyForce(b,b.position,{x:(Math.random()-.5)*.00055,y:-.0002-Math.random()*.00015})}
function preview(){if(s.running)return;s.rankings=[];s.winnerShown=false;el.winner.classList.add("hidden");renderRanks();sync();init();s.engine.timing.timeScale=.08;setTimeout(()=>{if(s.engine&&!s.running)s.engine.timing.timeScale=0},100);el.status.textContent="READY TO RACE";el.rankingPanel.classList.remove("race-running")}
function reset(){s.running=false;s.rankings=[];s.winnerShown=false;el.startRace.disabled=false;el.startRace.querySelector("span").textContent="START RACE";el.winner.classList.add("hidden");el.countdown.textContent="";preview()}
function confetti(){el.confetti.innerHTML="";const cs=["#55e7ff","#b7ff5a","#ffc857","#ff63c3","#7c8cff"];for(let i=0;i<65;i++){const p=document.createElement("i");p.className="confetti";p.style.left=`${Math.random()*100}%`;p.style.top=`${-5-Math.random()*20}%`;p.style.background=cs[i%cs.length];p.style.animationDelay=`${Math.random()*.5}s`;p.style.animationDuration=`${1.4+Math.random()*1.4}s`;el.confetti.appendChild(p)}setTimeout(()=>el.confetti.innerHTML="",3200)}
el.numberTab.addEventListener("click",()=>setMode("number"));el.customTab.addEventListener("click",()=>setMode("custom"));el.apply.addEventListener("click",range);el.input.addEventListener("input",()=>{if(s.mode==="custom")custom()});el.shuffle.addEventListener("click",()=>{s.labels=shuffle(s.labels);el.input.value=s.labels.join(", ");msg("순서를 섞었습니다.");setTimeout(()=>msg(),900)});el.mapGrid.addEventListener("click",e=>{const c=e.target.closest("[data-map]");if(c)setMap(c.dataset.map)});el.randomMap.addEventListener("click",()=>{const m=maps.filter(m=>m.id!==s.map);setMap(m[Math.floor(Math.random()*m.length)].id)});el.winnerMode.addEventListener("click",e=>{const b=e.target.closest("[data-winner]");if(b)setWinner(b.dataset.winner)});el.startRace.addEventListener("click",race);el.reset.addEventListener("click",reset);el.shake.addEventListener("click",shakeRace);el.speed.forEach(b=>b.addEventListener("click",()=>setSpeed(Number(b.dataset.speed))));el.again.addEventListener("click",()=>{reset();setTimeout(race,80)});range();setMap("neon-grid");addEventListener("pagehide",destroy,{once:true});