window.QUIZ_SETS = [
  {
    id:'test-chem-2026-09-01-v2',date:'2026-09-01',test:true,sync:false,required:false,subject:'물질과 에너지',range:'TEST · 기체 단원 문제 형식 미리보기',title:'화학 테스트 · 기체 법칙',note:'테스트용 세트. 진도에는 반영하지 않는다.',
    questions:[{type:'개념',prompt:'온도와 기체량이 일정할 때 부피를 줄이면 압력은?',choices:['감소','증가','일정','0'],answer:1,explanation:'보일 법칙에 따라 부피와 압력은 반비례한다.',tip:'P↑, V↓.',remediation:[{prompt:'같은 조건에서 부피가 1/2이면 압력은?',choices:['1/2배','같음','2배','4배'],answer:2,explanation:'PV 일정이므로 2배이다.',tip:'역수 관계.'},{prompt:'표에서 보일 법칙을 따르는 조합은?',visual:{type:'table',headers:['상태','P','V'],rows:[['A','1','4'],['B','2','2']]},choices:['A만','B만','A와 B','둘 다 아님'],answer:2,explanation:'두 상태 모두 PV=4이다.',tip:'PV를 확인한다.'}]}]
  },
  {
    id:'test-physics-2026-09-01-v2',date:'2026-09-01',test:true,sync:false,required:false,subject:'역학과 에너지',range:'TEST · 벡터 형식 미리보기',title:'물리 테스트 · 벡터',note:'테스트용 세트. 진도에는 반영하지 않는다.',
    questions:[{type:'그림·벡터',prompt:'서로 수직인 3 N과 4 N의 합력 크기는?',visual:{type:'vectors',vectors:[{x:90,y:0,label:'3 N'},{x:0,y:120,label:'4 N'}],resultant:{x:90,y:120,label:'R'}},choices:['1 N','5 N','7 N','12 N'],answer:1,explanation:'√(3²+4²)=5 N이다.',tip:'수직이면 피타고라스.',remediation:[{prompt:'서로 수직인 5 N과 12 N의 합력은?',choices:['7 N','13 N','17 N','60 N'],answer:1,explanation:'13 N이다.',tip:'5-12-13.'},{prompt:'서로 수직인 6 N과 8 N의 합력은?',choices:['2 N','10 N','14 N','48 N'],answer:1,explanation:'10 N이다.',tip:'6-8-10.'}]}]
  },
  {
    id:'2026-09-02',date:'2026-09-02',deadline:'2026-09-03T23:59:59+09:00',subject:'역학과 에너지',range:'힘의 합성·분해 / 벡터 기초 / 포물선 운동 진입 + 물질과 에너지 p.10~25 기체 보조',title:'9월 2일 · 벡터와 포물선 첫걸음',note:'물리는 그림에서 방향과 성분을 먼저 표시하고, 화학은 조건·단위·절대온도를 먼저 확인한다. 틀린 문제마다 비슷한 문제 2개를 풀고, 맞힌 것은 끝내고 틀린 것만 다시 푼다.',
    questions:[
      {type:'개념',prompt:'다음 중 벡터량만으로 묶인 것은?',choices:['질량, 시간','속력, 거리','힘, 속도','온도, 에너지'],answer:2,explanation:'힘과 속도는 크기뿐 아니라 방향까지 있어야 완전히 표현되는 벡터량이다.',tip:'문제에서 방향이 바뀌면 값 자체가 달라지는지 생각한다.',remediation:[{prompt:'다음 중 방향을 함께 표시해야 하는 물리량은?',choices:['질량','시간','가속도','온도'],answer:2,explanation:'가속도는 크기와 방향을 가지는 벡터량이다.',tip:'속도·가속도·힘·변위는 대표적인 벡터량이다.'},{prompt:'자동차가 같은 속력 10 m/s로 동쪽과 서쪽으로 각각 움직였다. 서로 다른 물리량은?',choices:['속력만 다르다','속도만 다르다','질량만 다르다','시간만 다르다'],answer:1,explanation:'속력은 같지만 방향이 반대이므로 속도는 서로 다르다.',tip:'속도=속력+방향.'}]},
      {type:'그림·합성',prompt:'그림처럼 한 물체에 오른쪽 6 N과 왼쪽 2 N의 힘이 동시에 작용한다. 합력은?',visual:{type:'vectors',vectors:[{x:150,y:0,label:'6 N'},{x:-70,y:0,label:'2 N'}],resultant:{x:100,y:0,label:'R'},caption:'두 힘은 같은 직선 위에서 반대 방향으로 작용한다.'},choices:['오른쪽 4 N','왼쪽 4 N','오른쪽 8 N','0 N'],answer:0,explanation:'반대 방향의 힘은 크기를 빼고, 더 큰 힘의 방향을 따른다. 6-2=4 N이므로 오른쪽 4 N이다.',tip:'방향 확인 → 같은 방향이면 더하기, 반대면 빼기.',remediation:[{prompt:'오른쪽 9 N과 왼쪽 5 N이 작용한다. 합력은?',choices:['오른쪽 4 N','왼쪽 4 N','오른쪽 14 N','0 N'],answer:0,explanation:'9-5=4 N이고 더 큰 힘이 오른쪽이므로 오른쪽 4 N이다.',tip:'크기 차이와 큰 힘의 방향을 함께 쓴다.'},{prompt:'그림처럼 두 힘이 같은 직선 위에 작용한다. 합력은?',visual:{type:'vectors',vectors:[{x:110,y:0,label:'4 N'},{x:-110,y:0,label:'4 N'}],resultant:{x:0,y:0,label:'R=0'},caption:'서로 반대 방향이고 크기는 같다.'},choices:['오른쪽 8 N','왼쪽 8 N','0 N','오른쪽 4 N'],answer:2,explanation:'크기가 같은 반대 방향 힘은 서로 상쇄되어 합력이 0 N이다.',tip:'같은 크기+반대 방향=상쇄.'}]},
      {type:'계산·벡터',prompt:'서로 수직인 6 N과 8 N의 힘이 한 물체에 작용한다. 합력의 크기는?',visual:{type:'vectors',vectors:[{x:120,y:0,label:'6 N'},{x:0,y:160,label:'8 N'}],resultant:{x:120,y:160,label:'R'},caption:'두 힘은 서로 수직이다.'},choices:['2 N','10 N','14 N','48 N'],answer:1,explanation:'수직 성분의 합력은 직각삼각형의 빗변이므로 √(6²+8²)=10 N이다.',tip:'수직 두 벡터면 피타고라스부터 확인한다.',remediation:[{prompt:'서로 수직인 9 N과 12 N의 합력 크기는?',choices:['3 N','15 N','21 N','108 N'],answer:1,explanation:'√(9²+12²)=15 N이다.',tip:'9-12-15는 3-4-5의 3배.'},{prompt:'그림의 두 수직 힘의 합력 크기는?',visual:{type:'vectors',vectors:[{x:60,y:0,label:'3 N'},{x:0,y:80,label:'4 N'}],resultant:{x:60,y:80,label:'R'}},choices:['1 N','5 N','7 N','12 N'],answer:1,explanation:'√(3²+4²)=5 N이다.',tip:'그림의 길이보다 표시된 힘의 값을 사용한다.'}]},
      {type:'개념·분해',prompt:'오른쪽 위 방향의 힘 F를 수평 성분과 수직 성분으로 분해했다. 반드시 옳은 설명은?',choices:['두 성분은 서로 수직이다','두 성분의 크기를 단순히 더하면 항상 F이다','수평 성분만으로 원래 힘의 방향을 알 수 있다','분해하면 원래 힘보다 에너지가 줄어든다'],answer:0,explanation:'직교좌표에서 힘을 분해하면 수평 성분과 수직 성분은 서로 수직이고, 두 성분의 벡터합이 원래 힘 F가 된다.',tip:'분해는 힘을 없애는 것이 아니라 같은 벡터를 두 축으로 표현하는 것이다.',remediation:[{prompt:'한 벡터를 x, y 성분으로 분해했을 때 원래 벡터는 어떻게 얻는가?',choices:['두 성분을 벡터로 더한다','두 성분을 항상 뺀다','큰 성분만 남긴다','두 성분을 곱한다'],answer:0,explanation:'x, y 성분을 벡터로 합성하면 원래 벡터가 된다.',tip:'분해와 합성은 서로 반대 과정이다.'},{prompt:'오른쪽 3 N과 위쪽 4 N을 성분으로 갖는 힘의 크기는?',choices:['1 N','5 N','7 N','12 N'],answer:1,explanation:'서로 수직인 성분이므로 √(3²+4²)=5 N이다.',tip:'성분에서 원래 크기를 구할 때 피타고라스를 쓴다.'}]},
      {type:'표·자료해석',prompt:'표는 세 물체에 작용하는 수평방향 힘을 나타낸다. 합력이 0인 물체는?',visual:{type:'table',headers:['물체','오른쪽 힘','왼쪽 힘'],rows:[['A','5 N','2 N'],['B','4 N','4 N'],['C','3 N','7 N']],caption:'모든 힘은 같은 직선 위에서 작용한다.'},choices:['A','B','C','A와 C'],answer:1,explanation:'B는 오른쪽 4 N과 왼쪽 4 N이 상쇄되어 합력이 0이다.',tip:'표 문제도 방향별 합을 따로 계산한다.',remediation:[{prompt:'합력이 0인 경우 반드시 옳은 것은?',choices:['물체가 반드시 정지한다','가속도가 0이다','속력이 반드시 0이다','운동 방향이 계속 바뀐다'],answer:1,explanation:'합력이 0이면 뉴턴의 제2법칙에 따라 가속도가 0이다. 정지 또는 등속 직선 운동이 가능하다.',tip:'합력 0과 속도 0은 다른 말이다.'},{prompt:'다음 표에서 왼쪽으로 3 N의 합력을 받는 물체는?',visual:{type:'table',headers:['물체','오른쪽 힘','왼쪽 힘'],rows:[['D','6 N','3 N'],['E','2 N','5 N'],['F','7 N','7 N']]},choices:['D','E','F','없음'],answer:1,explanation:'E는 왼쪽 5 N-오른쪽 2 N=왼쪽 3 N이다.',tip:'큰 쪽 방향을 마지막에 적는다.'}]},
      {type:'궤적·개념',prompt:'공기 저항을 무시한 포물선 운동이다. 빨간 점이 최고점일 때 옳은 것은?',visual:{type:'trajectory',highlight:3,points:[[0,0],[1,1.5],[2,2.35],[3,2.7],[4,2.35],[5,1.5],[6,0]],caption:'물체는 왼쪽에서 오른쪽으로 운동한다.'},choices:['속도 전체가 0이다','수평 속도 성분은 남고 수직 속도 성분만 0이다','가속도가 0이다','중력의 방향이 위쪽으로 바뀐다'],answer:1,explanation:'최고점에서는 위로 가던 수직 속도 성분이 순간적으로 0이지만 수평 속도는 계속 남는다. 중력가속도는 계속 아래쪽이다.',tip:'최고점: v_y=0, v_x≠0, a는 아래쪽.',remediation:[{prompt:'포물선 운동의 최고점에서 가속도의 방향은?',choices:['오른쪽','왼쪽','위쪽','아래쪽'],answer:3,explanation:'공기 저항을 무시하면 운동 내내 중력가속도만 작용하므로 아래쪽이다.',tip:'최고점에서도 중력은 사라지지 않는다.'},{prompt:'그림의 최고점에서 속도 방향은?',visual:{type:'trajectory',highlight:2,points:[[0,0],[1,1.4],[2,1.9],[3,1.4],[4,0]],caption:'물체는 오른쪽으로 진행한다.'},choices:['수평 오른쪽','수평 왼쪽','수직 위쪽','속도 0'],answer:0,explanation:'최고점에서 수직 속도 성분이 0이므로 속도는 수평 오른쪽이다.',tip:'속도는 궤적의 접선 방향이다.'}]},
      {type:'자료·운동',prompt:'공기 저항을 무시한 포물선 운동에서 수평 속도 vₓ와 수직 속도 vᵧ에 대한 설명으로 옳은 것은?',choices:['vₓ와 vᵧ가 모두 일정하다','vₓ는 일정하고 vᵧ는 중력 때문에 변한다','vₓ는 중력 때문에 변하고 vᵧ는 일정하다','최고점 이후에는 vₓ가 반대 방향이 된다'],answer:1,explanation:'중력은 수직 방향으로만 작용하므로 수평 가속도는 0이고 vₓ는 일정하다. vᵧ는 중력가속도에 의해 계속 변한다.',tip:'포물선은 수평 등속 운동+수직 등가속도 운동으로 나눠 본다.',remediation:[{prompt:'포물선 운동에서 공기 저항이 없을 때 수평방향 가속도는?',choices:['0','g','-g','속도와 같다'],answer:0,explanation:'수평 방향으로 작용하는 힘이 없으므로 수평 가속도는 0이다.',tip:'중력은 수직 아래 방향.'},{prompt:'같은 높이에서 던진 두 물체의 수평 속도만 다르고 초기 수직 속도와 중력이 같다면, 공중에 머무는 시간은?',choices:['수평 속도가 큰 쪽이 더 길다','수평 속도가 작은 쪽이 더 길다','같다','질량에 따라 달라진다'],answer:2,explanation:'공중에 머무는 시간은 수직 운동으로 결정되므로 수평 속도와 무관하다.',tip:'수평과 수직 운동을 독립적으로 본다.'}]},
      {type:'화학·개념',prompt:'온도와 압력이 일정할 때 기체의 양을 2배로 늘리면 부피는 어떻게 되는가?',choices:['1/2배','변하지 않음','2배','4배'],answer:2,explanation:'아보가드로 법칙에 따라 온도와 압력이 일정하면 기체 부피 V는 기체의 양 n에 정비례한다.',tip:'T, P 일정 → V∝n.',remediation:[{prompt:'같은 온도와 압력에서 0.5 mol 기체의 부피가 12 L라면 1.5 mol의 부피는?',choices:['4 L','12 L','24 L','36 L'],answer:3,explanation:'기체량이 3배이므로 부피도 3배인 36 L이다.',tip:'같은 T,P에서는 몰수 비=부피 비.'},{prompt:'표에서 같은 T,P를 유지할 때 ?에 들어갈 값은?',visual:{type:'table',headers:['상태','기체량(mol)','부피(L)'],rows:[['A','1.0','20'],['B','2.5','?']]},choices:['8','20','40','50'],answer:3,explanation:'V/n 일정이므로 2.5배의 기체량은 2.5배의 부피 50 L를 차지한다.',tip:'아보가드로 법칙은 V/n 일정.'}]},
      {type:'화학·계산',prompt:'27 ℃, 1.0 atm에서 이상 기체 0.20 mol의 부피는? (R=0.082 L·atm/(mol·K))',choices:['2.46 L','4.92 L','8.20 L','24.6 L'],answer:1,explanation:'27 ℃=300 K. PV=nRT에서 V=0.20×0.082×300/1.0=4.92 L이다.',tip:'PV=nRT 전에 ℃→K, 압력 atm, 부피 L를 확인한다.',remediation:[{prompt:'300 K, 2.0 atm에서 이상 기체 0.40 mol의 부피는? (R=0.082)',choices:['2.46 L','4.92 L','9.84 L','19.68 L'],answer:1,explanation:'V=nRT/P=0.40×0.082×300/2=4.92 L이다.',tip:'압력이 분모에 들어간다.'},{prompt:'표의 기체 상태에서 몰수 n은? (R=0.082)',visual:{type:'table',headers:['P(atm)','V(L)','T(K)'],rows:[['1.0','4.92','300']]},choices:['0.10 mol','0.20 mol','0.50 mol','2.0 mol'],answer:1,explanation:'n=PV/RT=4.92/(0.082×300)=0.20 mol이다.',tip:'구하는 문자를 식 한쪽에 먼저 정리한다.'}]},
      {type:'화학·자료해석',prompt:'같은 온도와 압력에서 기체 A와 B의 밀도가 각각 1.0 g/L, 2.0 g/L이다. 분자량의 관계로 옳은 것은?',visual:{type:'table',headers:['기체','밀도(g/L)','온도','압력'],rows:[['A','1.0','같음','같음'],['B','2.0','같음','같음']]},choices:['M_A=2M_B','M_A=M_B','M_B=2M_A','밀도로는 비교할 수 없다'],answer:2,explanation:'이상 기체에서 M=dRT/P이므로 같은 T,P에서는 분자량 M이 밀도 d에 정비례한다. B의 밀도가 2배이므로 분자량도 2배이다.',tip:'같은 T,P이면 M∝d.',remediation:[{prompt:'같은 T,P에서 기체 X의 밀도가 Y의 3배이다. 분자량 관계는?',choices:['M_X=⅓M_Y','M_X=M_Y','M_X=3M_Y','M_X=9M_Y'],answer:2,explanation:'같은 T,P에서는 M=dRT/P이므로 M∝d이다.',tip:'조건이 같을 때 비례식을 바로 쓴다.'},{prompt:'다음 표에서 분자량이 가장 큰 기체는? 모든 기체의 T,P는 같다.',visual:{type:'table',headers:['기체','밀도(g/L)'],rows:[['P','0.8'],['Q','1.4'],['R','2.1']]},choices:['P','Q','R','모두 같다'],answer:2,explanation:'같은 T,P에서는 밀도가 클수록 분자량이 크므로 R이 가장 크다.',tip:'M∝d는 동일 T,P 조건에서만 바로 적용한다.'}]}
    ]
  },
  {
    id:'2026-09-03',date:'2026-09-03',deadline:'2026-09-04T23:59:59+09:00',subject:'물질과 에너지',range:'혼합 기체 p.26~32 · 부분 압력·몰분율·수상 치환 + 포물선 운동 복습',title:'9월 3일 · 혼합 기체와 부분 압력',note:'혼합 기체는 먼저 전체 압력과 각 성분의 부분 압력을 구분한다. 틀린 문제마다 비슷한 문제 2개를 풀고, 맞힌 것은 끝내고 틀린 것만 다시 푼다.',
    questions:[
      {type:'표·자료해석',prompt:'같은 온도와 부피의 용기에서 서로 반응하지 않는 기체 A 2 mol과 B 3 mol을 혼합했다. 표의 관계로 옳은 것은?',visual:{type:'table',headers:['성분','기체량(mol)','몰분율'],rows:[['A','2','?'],['B','3','?']],caption:'전체 기체량은 5 mol이다.'},choices:['x_A=2/3, x_B=3/2','x_A=2/5, x_B=3/5','x_A=3/5, x_B=2/5','두 몰분율의 합은 5'],answer:1,explanation:'몰분율은 각 성분의 몰수를 전체 몰수로 나눈 값이다. 따라서 x_A=2/5, x_B=3/5이고 합은 1이다.',tip:'몰분율 = 성분 mol ÷ 전체 mol.',remediation:[{prompt:'기체 X 1 mol과 Y 4 mol이 섞여 있다. X의 몰분율은?',choices:['1/5','1/4','4/5','5'],answer:0,explanation:'전체가 5 mol이므로 X의 몰분율은 1/5이다.',tip:'분모는 항상 전체 몰수.'},{prompt:'표의 혼합 기체에서 B의 몰분율은?',visual:{type:'table',headers:['성분','mol'],rows:[['A','3'],['B','6'],['C','1']],caption:'세 기체는 서로 반응하지 않는다.'},choices:['0.1','0.3','0.6','0.9'],answer:2,explanation:'전체 10 mol 중 B가 6 mol이므로 x_B=0.6이다.',tip:'몰분율의 총합은 1이다.'}]},
      {type:'개념',prompt:'서로 반응하지 않는 기체 A와 B의 혼합 기체에서 전체 압력 P와 부분 압력 P_A, P_B의 관계로 옳은 것은?',choices:['P=P_A-P_B','P=P_A+P_B','P=P_A×P_B','P_A=P_B가 항상 성립한다'],answer:1,explanation:'부분 압력 법칙에 따라 혼합 기체의 전체 압력은 각 성분 기체의 부분 압력의 합이다.',tip:'전체 압력 = 부분 압력들의 합.',remediation:[{prompt:'A, B, C의 부분 압력이 각각 1.0 atm, 0.8 atm, 0.2 atm이다. 전체 압력은?',choices:['0.2 atm','1.0 atm','1.8 atm','2.0 atm'],answer:3,explanation:'1.0+0.8+0.2=2.0 atm이다.',tip:'부분 압력을 모두 더한다.'},{prompt:'표에서 전체 압력이 5.0 atm일 때 C의 부분 압력은?',visual:{type:'table',headers:['성분','부분 압력(atm)'],rows:[['A','2.0'],['B','1.5'],['C','?']]},choices:['0.5','1.0','1.5','3.5'],answer:2,explanation:'5.0-2.0-1.5=1.5 atm이다.',tip:'모르는 부분 압력 = 전체-나머지 합.'}]},
      {type:'계산',prompt:'같은 온도와 부피에서 A 2 mol, B 6 mol이 섞인 혼합 기체의 전체 압력이 4.0 atm이다. A의 부분 압력은?',choices:['0.5 atm','1.0 atm','2.0 atm','3.0 atm'],answer:1,explanation:'A의 몰분율은 2/(2+6)=1/4이고, P_A=x_A P=1/4×4.0=1.0 atm이다.',tip:'부분 압력 = 몰분율 × 전체 압력.',remediation:[{prompt:'X 3 mol, Y 1 mol의 혼합 기체 전체 압력이 8.0 atm이다. Y의 부분 압력은?',choices:['1.0 atm','2.0 atm','4.0 atm','6.0 atm'],answer:1,explanation:'Y의 몰분율은 1/4이므로 부분 압력은 8.0×1/4=2.0 atm이다.',tip:'먼저 몰분율부터 구한다.'},{prompt:'표의 혼합 기체에서 전체 압력이 6.0 atm일 때 A의 부분 압력은?',visual:{type:'table',headers:['성분','mol'],rows:[['A','4'],['B','2']]},choices:['2.0 atm','3.0 atm','4.0 atm','6.0 atm'],answer:2,explanation:'A의 몰분율은 4/6=2/3이므로 P_A=6.0×2/3=4.0 atm이다.',tip:'같은 T,V에서는 압력 비=몰수 비.'}]},
      {type:'표·자료해석',prompt:'같은 온도와 부피에서 기체 A와 B를 따로 넣었을 때 압력이 각각 3 atm, 2 atm이었다. 두 기체를 같은 용기에 함께 넣었을 때 전체 압력은?',visual:{type:'table',headers:['상태','A의 압력','B의 압력'],rows:[['혼합 전','3 atm','2 atm']],caption:'온도와 용기 부피는 혼합 전후 같고 A와 B는 반응하지 않는다.'},choices:['1 atm','2.5 atm','5 atm','6 atm'],answer:2,explanation:'같은 온도와 부피에서 각 기체가 나타내는 압력이 각각 부분 압력이 되므로 전체 압력은 3+2=5 atm이다.',tip:'혼합 전후 T,V가 같다는 조건을 확인한다.',remediation:[{prompt:'같은 T,V에서 A만 있을 때 1.2 atm, B만 있을 때 0.8 atm이었다. 혼합 후 전체 압력은?',choices:['0.4 atm','1.0 atm','2.0 atm','9.6 atm'],answer:2,explanation:'부분 압력의 합 1.2+0.8=2.0 atm이다.',tip:'조건이 같으면 각 단독 압력을 부분 압력으로 볼 수 있다.'},{prompt:'다음 표의 세 기체를 같은 T,V에서 혼합할 때 전체 압력은?',visual:{type:'table',headers:['기체','단독 압력(atm)'],rows:[['A','0.5'],['B','1.0'],['C','1.5']]},choices:['1.0 atm','2.0 atm','2.5 atm','3.0 atm'],answer:3,explanation:'0.5+1.0+1.5=3.0 atm이다.',tip:'부분 압력 법칙은 성분이 3개 이상이어도 같다.'}]},
      {type:'개념·함정',prompt:'혼합 기체에서 성분 A의 몰분율이 0.30이고 전체 압력이 10 atm이다. 다음 설명 중 옳은 것은?',choices:['A의 부분 압력은 3 atm이다','A의 부분 압력은 30 atm이다','A의 몰수는 반드시 0.30 mol이다','나머지 모든 기체의 부분 압력 합은 3 atm이다'],answer:0,explanation:'P_A=x_A P=0.30×10=3 atm이다. 몰분율 0.30은 비율이지 몰수 자체가 아니다.',tip:'몰분율은 단위 없는 비율.',remediation:[{prompt:'몰분율이 0.25인 성분 B가 전체 압력 12 atm의 혼합 기체에 있다. B의 부분 압력은?',choices:['1 atm','3 atm','4 atm','48 atm'],answer:1,explanation:'12×0.25=3 atm이다.',tip:'x_i P.'},{prompt:'전체 압력이 8 atm이고 A의 부분 압력이 2 atm이다. A의 몰분율은?',choices:['0.20','0.25','0.40','4.0'],answer:1,explanation:'x_A=P_A/P=2/8=0.25이다.',tip:'몰분율 = 부분 압력 ÷ 전체 압력.'}]},
      {type:'그림·자료해석',prompt:'기체를 물 위에서 수상 치환으로 모았다. 눈금실린더 안과 밖의 수면 높이가 같고 대기압이 760 mmHg, 그 온도에서 물의 증기압이 20 mmHg이다. 모은 건조 기체의 압력은?',visual:{type:'table',headers:['대기압','수증기 부분 압력','실린더 안 전체 압력'],rows:[['760 mmHg','20 mmHg','760 mmHg']],caption:'수면 높이가 같으므로 실린더 안 전체 압력은 대기압과 같다.'},choices:['20 mmHg','740 mmHg','760 mmHg','780 mmHg'],answer:1,explanation:'실린더 안에는 목표 기체와 수증기가 함께 있으므로 P_전체=P_기체+P_수증기. 따라서 P_기체=760-20=740 mmHg이다.',tip:'수상 치환: 건조 기체 압력 = 대기압 - 수증기압.',remediation:[{prompt:'수상 치환으로 기체를 모았고 전체 압력이 1.00 atm, 수증기 부분 압력이 0.03 atm이다. 건조 기체 압력은?',choices:['0.03 atm','0.97 atm','1.00 atm','1.03 atm'],answer:1,explanation:'1.00-0.03=0.97 atm이다.',tip:'수증기를 빼야 목표 기체만 남는다.'},{prompt:'표의 조건에서 건조 기체의 압력은?',visual:{type:'table',headers:['실린더 안 전체 압력','수증기압'],rows:[['750 mmHg','25 mmHg']]},choices:['25 mmHg','725 mmHg','750 mmHg','775 mmHg'],answer:1,explanation:'750-25=725 mmHg이다.',tip:'전체=기체+수증기.'}]},
      {type:'계산·응용',prompt:'같은 온도에서 2.0 L 용기에 A 0.20 mol, B 0.30 mol이 들어 있다. 전체 압력이 5.0 atm이라면 B의 부분 압력은?',choices:['2.0 atm','2.5 atm','3.0 atm','5.0 atm'],answer:2,explanation:'전체 몰수는 0.50 mol, B의 몰분율은 0.30/0.50=0.60이므로 P_B=0.60×5.0=3.0 atm이다.',tip:'용기 부피가 주어져도 몰분율로 바로 풀 수 있으면 불필요한 값이다.',remediation:[{prompt:'A 0.10 mol, B 0.40 mol 혼합 기체의 전체 압력이 2.5 atm이다. A의 부분 압력은?',choices:['0.25 atm','0.50 atm','1.0 atm','2.0 atm'],answer:1,explanation:'A의 몰분율은 0.10/0.50=0.20, P_A=0.20×2.5=0.50 atm이다.',tip:'필요 없는 부피·온도 값에 흔들리지 않는다.'},{prompt:'표의 혼합 기체에서 전체 압력이 9 atm일 때 C의 부분 압력은?',visual:{type:'table',headers:['성분','mol'],rows:[['A','1'],['B','1'],['C','4']]},choices:['1.5 atm','3.0 atm','6.0 atm','9.0 atm'],answer:2,explanation:'C의 몰분율은 4/6=2/3이므로 9×2/3=6 atm이다.',tip:'부분 압력 비는 몰수 비와 같다.'}]},
      {type:'표·복합자료',prompt:'혼합 기체 A, B의 자료가 다음과 같다. 빈칸 (가), (나)의 값으로 옳은 것은?',visual:{type:'table',headers:['성분','몰분율','부분 압력(atm)'],rows:[['A','0.40','(가)'],['B','(나)','3.0']],caption:'전체 압력은 5.0 atm이다.'},choices:['(가) 2.0, (나) 0.60','(가) 2.0, (나) 0.40','(가) 3.0, (나) 0.60','(가) 5.0, (나) 0.60'],answer:0,explanation:'A의 부분 압력은 0.40×5.0=2.0 atm이고, 두 성분뿐이므로 B의 몰분율은 1-0.40=0.60이다.',tip:'몰분율 합=1, 부분 압력 합=전체 압력.',remediation:[{prompt:'전체 압력 10 atm인 A+B 혼합 기체에서 x_A=0.70이다. P_B는?',choices:['1 atm','3 atm','7 atm','10 atm'],answer:1,explanation:'x_B=0.30이므로 P_B=3 atm이다.',tip:'두 성분이면 남은 몰분율은 1-x.'},{prompt:'표의 빈칸에 들어갈 값은?',visual:{type:'table',headers:['성분','몰분율','부분 압력(atm)'],rows:[['X','0.25','1.5'],['Y','0.75','?']],caption:'두 기체만 존재한다.'},choices:['0.5 atm','1.5 atm','3.0 atm','4.5 atm'],answer:3,explanation:'X의 부분 압력 1.5 atm이 전체의 0.25이므로 전체 압력은 6 atm, Y는 0.75×6=4.5 atm이다.',tip:'한 성분으로 전체 압력을 역산할 수도 있다.'}]},
      {type:'궤적·누적복습',prompt:'공기 저항을 무시한 포물선 운동에서 물체가 최고점을 지난 직후의 속도와 가속도에 대한 설명으로 옳은 것은?',visual:{type:'trajectory',highlight:4,points:[[0,0],[1,1.5],[2,2.35],[3,2.7],[4,2.35],[5,1.5],[6,0]],caption:'물체는 왼쪽에서 오른쪽으로 운동한다.'},choices:['속도는 수평 오른쪽, 가속도는 0','속도는 오른쪽 아래, 가속도는 아래쪽','속도는 왼쪽 아래, 가속도는 아래쪽','속도는 오른쪽 위, 가속도는 위쪽'],answer:1,explanation:'최고점을 지난 뒤 수평 속도는 오른쪽으로 유지되고 수직 속도는 아래쪽이므로 전체 속도는 오른쪽 아래다. 가속도는 항상 중력 방향인 아래쪽이다.',tip:'속도 방향과 가속도 방향을 따로 판단한다.',remediation:[{prompt:'포물선 운동의 최고점 바로 전 속도 방향과 가속도 방향으로 옳은 것은?',choices:['오른쪽 위 / 아래쪽','오른쪽 아래 / 아래쪽','오른쪽 위 / 위쪽','수평 오른쪽 / 0'],answer:0,explanation:'최고점 전에는 수직 속도가 위쪽이고 수평 속도는 오른쪽이므로 속도는 오른쪽 위, 가속도는 아래쪽이다.',tip:'가속도는 위치와 무관하게 아래쪽.'},{prompt:'그림의 최고점에서 옳은 것은?',visual:{type:'trajectory',highlight:2,points:[[0,0],[1,1.3],[2,1.8],[3,1.3],[4,0]],caption:'오른쪽으로 던진 물체'},choices:['수평 속도 0, 수직 속도 0','수평 속도는 남고 수직 속도는 0','가속도가 0','가속도가 오른쪽'],answer:1,explanation:'최고점에서도 수평 속도는 유지되고 수직 속도만 순간적으로 0이다.',tip:'최고점 v_y=0, v_x≠0.'}]},
      {type:'개념·누적복습',prompt:'공기 저항이 없을 때 같은 높이에서 같은 초기 수직 속도로 던진 두 물체 A, B의 수평 속도가 서로 다르다. 공중에 머무는 시간에 대한 설명으로 옳은 것은?',choices:['A가 항상 더 길다','B가 항상 더 길다','두 물체가 같다','수평 속도가 큰 쪽이 항상 2배 길다'],answer:2,explanation:'공중에 머무는 시간은 수직 운동으로 결정된다. 초기 수직 속도와 높이가 같으면 수평 속도가 달라도 체공 시간은 같다.',tip:'포물선은 수평과 수직을 독립적으로 본다.',remediation:[{prompt:'수평 속도만 2배가 되고 수직 운동 조건은 같을 때 체공 시간은 어떻게 되는가?',choices:['1/2배','같다','2배','4배'],answer:1,explanation:'체공 시간은 수직 운동 조건으로 결정되므로 변하지 않는다.',tip:'수평 속도는 수평 이동거리만 바꾼다.'},{prompt:'같은 높이에서 수평으로 던진 두 물체의 수평 속도가 각각 5 m/s, 10 m/s이다. 공기 저항을 무시하면 바닥에 도달하는 시간은?',choices:['5 m/s가 더 짧다','10 m/s가 더 짧다','같다','질량을 알아야 한다'],answer:2,explanation:'두 물체의 수직 초기 속도와 낙하 높이가 같아 낙하 시간도 같다.',tip:'수평투사에서도 낙하 시간은 수직 운동만 본다.'}]}
    ]
  }
];
