window.QUIZ_SETS = [
  {
    id:'test-chem-2026-09-01',date:'2026-09-01',test:true,sync:false,required:false,subject:'물질과 에너지',range:'TEST · 기체 단원 문제 형식 미리보기',title:'화학 테스트 · 기체 법칙',note:'오늘은 기능과 문제 형식을 확인하는 테스트용이다. 점수와 진도는 반영하지 않는다. 내일부터 완자 실제 진도에 맞춰 정식 문제를 낸다.',
    questions:[
      {type:'그림·개념',prompt:'같은 온도에서 같은 양의 기체가 다음과 같이 A에서 B로 압축되었다. 옳은 설명은?',visual:{type:'piston',states:[{label:'A',height:.82,particles:8,pressure:'P₁'},{label:'B',height:.42,particles:8,pressure:'P₂'}],caption:'피스톤 내부의 기체 입자 수와 온도는 일정하다.'},choices:['P₂<P₁이고 충돌 횟수도 감소한다','P₂>P₁이고 벽과의 충돌 횟수가 증가한다','P₂=P₁이고 부피만 감소한다','기체 분자 수가 자동으로 감소한다'],answer:1,explanation:'온도와 기체량이 일정할 때 부피가 감소하면 벽과의 충돌 빈도가 증가해 압력이 커진다.',tip:'보일 법칙은 P↑, V↓.',remediation:[{prompt:'같은 조건에서 부피가 처음의 1/3이 되면 압력은?',choices:['1/3배','같음','3배','9배'],answer:2,explanation:'PV가 일정하므로 부피가 1/3이면 압력은 3배.',tip:'배수는 역수.'}]},
      {type:'계산',prompt:'온도와 기체량이 일정하다. 1.2 atm에서 500 mL인 기체를 2.0 atm으로 압축하면 최종 부피는?',choices:['200 mL','300 mL','500 mL','833 mL'],answer:1,explanation:'P₁V₁=P₂V₂에서 1.2×500=2.0×V₂, V₂=300 mL.',tip:'압력이 커졌으므로 답은 500 mL보다 작아야 한다.'},
      {type:'그래프·자료해석',prompt:'다음 P-V 자료는 같은 온도, 같은 기체량에서 측정한 것이다. 그래프의 관계를 가장 잘 설명한 것은?',visual:{type:'graph',xLabel:'P (상대값)',yLabel:'V (상대값)',points:[[1,4],[2,2],[4,1]],caption:'점들은 동일한 기체의 서로 다른 상태를 나타낸다.'},choices:['P와 V는 정비례한다','P와 V는 반비례한다','P+V가 일정하다','온도가 증가할수록 P와 V가 동시에 감소한다'],answer:1,explanation:'P가 2배가 될 때 V가 1/2배가 되어 PV가 일정한 보일 관계이다.',tip:'그래프에서도 배수 관계를 먼저 본다.',remediation:[{prompt:'P=2일 때 V=3인 상태가 보일 법칙을 따른다. P=6일 때 V는?',choices:['1','2','6','9'],answer:0,explanation:'2×3=6×V이므로 V=1.',tip:'그래프 문제도 결국 PV 일정.'}]},
      {type:'계산',prompt:'압력과 기체량이 일정한 기체가 27 ℃에서 150 mL이다. 327 ℃에서는 부피가 얼마인가?',choices:['75 mL','150 mL','225 mL','300 mL'],answer:3,explanation:'27 ℃=300 K, 327 ℃=600 K. 절대온도가 2배이므로 부피도 2배.',tip:'샤를 법칙에서는 반드시 K로 변환한다.'},
      {type:'표·자료해석',prompt:'표의 A와 B는 같은 양의 기체이다. A→B에서 압력이 일정하다고 할 때 ?에 들어갈 값은?',visual:{type:'table',headers:['상태','온도(K)','부피(mL)','압력'],rows:[['A','300','240','일정'],['B','450','?','일정']],caption:'기체량과 압력은 일정하다.'},choices:['160 mL','240 mL','360 mL','450 mL'],answer:2,explanation:'V/T 일정이므로 240/300=V/450, V=360 mL.',tip:'표를 보면 먼저 무엇이 고정인지 표시.'},
      {type:'개념·함정',prompt:'27 ℃에서 54 ℃로 가열하면 섭씨온도가 2배가 된다. 압력이 일정할 때 기체 부피도 정확히 2배가 되는가?',choices:['그렇다. 섭씨가 2배이기 때문이다','아니다. 300 K→327 K이므로 조금 증가한다','아니다. 부피는 감소한다','온도와 부피는 관계없다'],answer:1,explanation:'샤를 법칙은 섭씨가 아니라 절대온도에 대한 비례 관계이다.',tip:'℃ 숫자만 보고 배수 판단 금지.'}
    ]
  },
  {
    id:'test-physics-2026-09-01',date:'2026-09-01',test:true,sync:false,required:false,subject:'역학과 에너지',range:'TEST · 힘의 합성 / 운동 자료 형식 미리보기',title:'물리 테스트 · 벡터와 운동',note:'아직 배우지 않은 내용이 섞여 있어 정답을 몰라도 된다. 실제 정식 진도는 내일부터 완자 순서대로 진행한다. 오늘은 그림·그래프 문제와 오답보강이 어떻게 나오는지 확인하는 용도다.',
    questions:[
      {type:'그림·벡터',prompt:'한 물체에 서로 수직인 3 N과 4 N의 힘이 동시에 작용한다. 합력의 크기는?',visual:{type:'vectors',vectors:[{x:90,y:0,label:'3 N'},{x:0,y:120,label:'4 N'}],resultant:{x:90,y:120,label:'R'},caption:'두 힘은 서로 수직이다.'},choices:['1 N','5 N','7 N','12 N'],answer:1,explanation:'서로 수직인 벡터의 합력은 피타고라스 관계로 √(3²+4²)=5 N.',tip:'수직이면 직각삼각형부터 본다.',remediation:[{prompt:'서로 수직인 5 N과 12 N의 합력 크기는?',choices:['7 N','13 N','17 N','60 N'],answer:1,explanation:'√(5²+12²)=13 N.',tip:'5-12-13 삼각형.'}]},
      {type:'개념',prompt:'다음 중 방향까지 함께 나타내야 완전히 표현되는 물리량은?',choices:['질량','시간','속력','힘'],answer:3,explanation:'힘은 크기와 방향을 가지는 벡터량이다.',tip:'힘·속도·가속도는 방향을 확인한다.'},
      {type:'그림·합성',prompt:'그림에서 두 힘 F₁, F₂가 같은 방향으로 작용한다. 합력의 방향과 크기에 대한 설명으로 옳은 것은?',visual:{type:'vectors',vectors:[{x:80,y:0,label:'F₁=2 N'},{x:130,y:0,label:'F₂=3 N'}],caption:'두 화살표는 같은 방향을 가리킨다.'},choices:['반대 방향 1 N','같은 방향 1 N','같은 방향 5 N','합력은 0 N'],answer:2,explanation:'같은 방향의 벡터는 크기를 더하므로 2+3=5 N.',tip:'같은 방향 더하기, 반대 방향 빼기.'},
      {type:'궤적·개념',prompt:'공기 저항을 무시한 포물선 운동에서 빨간 점이 최고점이라고 하자. 최고점에서 옳은 것은?',visual:{type:'trajectory',highlight:3,points:[[0,0],[1,1.5],[2,2.35],[3,2.7],[4,2.35],[5,1.5],[6,0]],caption:'수평 오른쪽으로 진행하는 물체의 궤적'},choices:['속도가 완전히 0이다','수직 속도 성분은 0이지만 수평 속도 성분은 남아 있다','가속도가 0이다','중력이 순간적으로 사라진다'],answer:1,explanation:'최고점에서는 수직 속도만 0이고 수평 속도는 유지된다. 중력가속도는 계속 아래 방향이다.',tip:'최고점에서 v_y=0이지 v 전체=0은 아니다.',remediation:[{prompt:'포물선 운동의 최고점에서도 계속 존재하는 것은?',choices:['아래 방향 중력가속도','위 방향 중력가속도','0인 수평속도','0인 중력'],answer:0,explanation:'중력가속도는 운동 내내 아래 방향으로 작용한다.',tip:'가속도와 속도를 구분.'}]},
      {type:'그림·판단',prompt:'다음 벡터 그림에서 빨간 점선 R이 두 파란 힘의 합력이라면 R의 방향은?',visual:{type:'vectors',vectors:[{x:95,y:0,label:'F₁'},{x:0,y:75,label:'F₂'}],resultant:{x:95,y:75,label:'R'},caption:'평행사변형법으로 합력을 나타낸 모습'},choices:['오른쪽 아래','왼쪽 위','오른쪽 위','왼쪽 아래'],answer:2,explanation:'오른쪽 힘과 위쪽 힘을 합치면 합력은 오른쪽 위 방향이다.',tip:'벡터 합성은 화살표 끝점의 대각선 방향.'},
      {type:'응용',prompt:'물체에 작용하는 합력이 0일 때 반드시 옳은 것은?',choices:['물체는 반드시 정지한다','물체의 속도는 반드시 증가한다','가속도는 0이다','운동 방향이 매 순간 바뀐다'],answer:2,explanation:'합력이 0이면 뉴턴의 제2법칙에 따라 가속도가 0이다. 정지해 있을 수도, 일정한 속도로 움직일 수도 있다.',tip:'합력 0 = 가속도 0, 반드시 정지는 아님.'}
    ]
  }
];
